[Node]
StartupTimeout = "20s"
ShutdownTimeout = "20s"
Store = "/home/celestia"

[Core]
IP = "rpc-mocha.pops.one"
Port = "9090"
TLSEnabled = false

[State]
DefaultKeyName = "my_celes_key"
DefaultBackendName = "test"

[P2P]
Network = "mocha"
ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic-v1/webtransport", "/ip4/0.0.0.0/udp/2121/quic-v1", "/ip4/0.0.0.0/udp/2121/webrtc-direct", "/ip4/0.0.0.0/tcp/2121"]
AnnounceAddresses = []
NoAnnounceAddresses = []
MutualPeers = []
PeerExchange = false
[P2P.ConnManager]
  Low = 50
  High = 100
  GracePeriod = "1m0s"

[RPC]
Address = "0.0.0.0"
Port = "26658"
SkipAuth = true

[Gateway]
Address = "localhost"
Port = "26659"
Enabled = false

[Share]
BlockStoreCacheSize = 128
UseShareExchange = true
[Share.EDSStoreParams]
  RecentBlocksCacheSize = 10
[Share.ShrExEDSParams]
  ServerReadTimeout = "5s"
  ServerWriteTimeout = "1m0s"
  HandleRequestTimeout = "1m0s"
  ConcurrencyLimit = 8
  BufferSize = 32768
[Share.ShrExNDParams]
  ServerReadTimeout = "5s"
  ServerWriteTimeout = "1m0s"
  HandleRequestTimeout = "1m0s"
  ConcurrencyLimit = 8
[Share.PeerManagerParams]
  PoolValidationTimeout = "2m0s"
  PeerCooldown = "3s"
  GcInterval = "30s"
  EnableBlackListing = false
[Share.LightAvailability]
  SampleAmount = 8
[Share.Discovery]
  PeersLimit = 2
  AdvertiseInterval = "1h0m0s"

[Header]
TrustedHash = "9C8A5323A4E68F47F2B9EAA01400E11BEAC8F779ACFF90469EECF57BF1FDE694"
TrustedPeers = []
TrustedHeight = 8040790
[Header.Store]
  StoreCacheSize = 512
  IndexCacheSize = 2048
  WriteBatchSize = 512
[Header.Syncer]
  TrustingPeriod = "336h0m0s"
[Header.Server]
  WriteDeadline = "8s"
  ReadDeadline = "1m0s"
  RequestTimeout = "10s"
[Header.Client]
  MaxHeadersPerRangeRequest = 64
  RequestTimeout = "8s"

[DASer]
SamplingRange = 128
ConcurrencyLimit = 8
BackgroundStoreInterval = "10m0s"
SampleFrom = 8040790
SampleTimeout = "2m40s"