[Node]
StartupTimeout = "20s"
ShutdownTimeout = "20s"

[Core]
IP = "rpc-mocha.pops.one"
Port = "9090"
TLSEnabled = false
XTokenPath = ""
AdditionalCoreEndpoints = []

[State]
DefaultKeyName = "my_celes_key"
DefaultBackendName = "test"
EstimatorAddress = ""
EnableEstimatorTLS = false

[P2P]
ListenAddresses = [
  "/ip4/0.0.0.0/udp/2121/quic-v1/webtransport",
  "/ip6/::/udp/2121/quic-v1/webtransport",
  "/ip4/0.0.0.0/udp/2121/quic-v1",
  "/ip6/::/udp/2121/quic-v1",
  "/ip4/0.0.0.0/udp/2121/webrtc-direct",
  "/ip6/::/udp/2121/webrtc-direct",
  "/ip4/0.0.0.0/tcp/2121",
  "/ip6/::/tcp/2121"
]
AnnounceAddresses = []
NoAnnounceAddresses = [
  "/ip4/127.0.0.1/udp/2121/quic-v1/webtransport",
  "/ip4/0.0.0.0/udp/2121/quic-v1/webtransport",
  "/ip6/::/udp/2121/quic-v1/webtransport",
  "/ip4/0.0.0.0/udp/2121/quic-v1",
  "/ip4/127.0.0.1/udp/2121/quic-v1",
  "/ip6/::/udp/2121/quic-v1",
  "/ip4/0.0.0.0/udp/2121/webrtc-direct",
  "/ip4/127.0.0.1/udp/2121/webrtc-direct",
  "/ip6/::/udp/2121/webrtc-direct",
  "/ip4/0.0.0.0/tcp/2121",
  "/ip4/127.0.0.1/tcp/2121",
  "/ip6/::/tcp/2121"
]
MutualPeers = []
PeerExchange = false

[P2P.ConnManager]
Low = 50
High = 100
GracePeriod = "1m0s"

[RPC]
Address = "0.0.0.0"
Port = "26658"
SkipAuth = true

[RPC.CORS]
Enabled = false
AllowedOrigins = []
AllowedHeaders = []
AllowedMethods = []

[Share]
BlockStoreCacheSize = 128
UseShareExchange = true
UseBitswap = true

[Share.EDSStoreParams]
RecentBlocksCacheSize = 10

[Share.ShrexClient]
ReadTimeout = "2m0s"
WriteTimeout = "5s"

[Share.ShrexServer]
ReadTimeout = "5s"
WriteTimeout = "1m0s"
HandleRequestTimeout = "1m0s"
ConcurrencyLimit = 10

[Share.PeerManagerParams]
PoolValidationTimeout = "2m0s"
PeerCooldown = "3s"
GcInterval = "30s"
EnableBlackListing = false

[Share.LightAvailability]
SampleAmount = 16

[Share.Discovery]
PeersLimit = 5
AdvertiseInterval = "1h0m0s"

[Header]
TrustedPeers = []

[Header.Store]
StoreCacheSize = 512
IndexCacheSize = 2048
WriteBatchSize = 16

[Header.Syncer]
PruningWindow = "169h0m0s"
# Set to a trusted hash to start syncing from a specific point. Leave empty to sync from genesis.
SyncFromHash = "C47B84E75B04EF42C6D5B6B06582BD577950A1FF8E6D1243BDFFEF9EBA5C611C"
# Set to a trusted height to start syncing from. Use 0 to disable.
SyncFromHeight = 8340332

[Header.Server]
WriteDeadline = "8s"
ReadDeadline = "1m0s"
RequestTimeout = "10s"

[Header.Client]
MaxHeadersPerRangeRequest = 64
RequestTimeout = "8s"

[DASer]
SamplingRange = 100
ConcurrencyLimit = 16
BackgroundStoreInterval = "10m0s"
SampleTimeout = "1m36s"
Enabled = true
